### ISSUE TITLE
Architecture documentation

### ISSUE THREAD

**Issue by DevVersion** [angular/material-tools#1]
We should have a file, explaining the architecture and the different concepts behind it, in detail.

**Comment by ThomasBurleson** [comment]
Please use [Gliffy](http://preview.gliffy.com/html5/api/editor) to create architecture diagrams that can be exported as images and embedded within an `architecture.md` document.

**Comment by DevVersion** [comment]
@ThomasBurleson Sure, I'll use them once I found any case, where some diagrams are appropriated. Can't think about anything right now.

**Comment by ThomasBurleson** [comment]
@DevVersion - please work on this soon. Angular Material v1.1.0 is being released this week and the `material-tools` is included in that announcement.

**Comment by DevVersion** [comment]
Closed with #18
