### ISSUE TITLE
problems to define right color for tabs

### ISSUE THREAD

**Issue by dohomi** [angular/material-tools#20]
Hi,
I just trying out the theme build and it worked very good so far. The only color which doesn't work for me is the color of `mdTabs`. I'm using following palette can somebody give me a hint what I miss out?
```javascript
var tools = new MaterialTools({
  destination: './output',
  version: '1.1.0',
  //modules: ['menu', 'checkbox'],
  theme: {
    primaryPalette: 'light-blue',
    backgroundPalette: 'grey'
  },
  palettes: {
    'light-blue': {
    'hue-1': '100',
    'hue-2': '200',
    'hue-3': '300',
		'50':'E1F5FE',
		'100':'B3E5FC',
		'200':'81D4FA',
		'300':'4FC3F7',
		'400':'29B6F6',
		'500':'01579B',
		'600':'039BE5',
		'700':'0288D1',
		'800':'0277BD',
		'900':'01579B',
		'A100':'80D8FF',
		'A200':'40C4FF',
		'A400':'00B0FF',
		'A700':'0091EA',
		'contrastDefaultColor': 'light',
    'contrastDarkColors': ['50', '100', '200', '300', '400', 'A100', 'A200'],
    'contrastStrongLightColors': ['500', '600', '700', '800', '900', 'A400', 'A700']
    }
  }
});
```
This is how the style looks like:
<img width="587" alt="screen shot 2016-09-01 at 19 12 23" src="https://cloud.githubusercontent.com/assets/489221/18176941/2557bd68-7078-11e6-8bc0-aeb48191faa8.png">

**Comment by crisbeto** [comment]
This is actually an issue with Material. We have a pending fix for it at https://github.com/angular/material/pull/9484

**Comment by dohomi** [comment]
Thanks @crisbeto for the quick reply
