### ISSUE TITLE
/usr/bin/env: "node\r" no such file or directory found

### ISSUE THREAD

**Issue by Jesus82** [angular/material-tools#27]
I have this problem under ubuntu 16.04

After installing globally with `sudo npm install -g angular-material-tools`, I type `angular-material --help`, and I get this error `/usr/bin/env: "node\r" no such file or directory found`
Any workaround? Thanks!

**Comment by DevVersion** [comment]
Thanks for the issue. We have fixed this with SHA https://github.com/angular/material-tools/commit/3dbea5610d831311a31058fd22aa87bc2811726b. A new release `beta.6` is also published.
