### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Szymon-dziewonski** [angular/material-tools#34]
Hey I just configured my js file 

```
'use strict';

const MaterialTools = require('angular-material-tools');

let tools = new MaterialTools({
  destination: '/',
  version    : '1.1.6',
  modules    : ['autocomplete', 'checkbox', 'input', 'progressLinear', 'radioButton', 'toolbar'],
  theme      : {
    primaryPalette   : 'indigo',
    accentPalette    : 'purple',
    warnPalette      : 'deep-orange',
    backgroundPalette: 'grey'
  }
});

const successHandler = () => console.log('Build was successful.');
const errorHandler   = error => console.error(error);

tools.build().then(successHandler).catch(errorHandler);         // Build all JS/CSS/themes

tools.build('js').then(successHandler).catch(errorHandler);     // Only build the JS.
tools.build('theme').then(successHandler).catch(errorHandler);  // Only build the theme.
tools.build('css').then(successHandler).catch(errorHandler);    // Only build the CSS

// You can also build a subset of files.
tools.build('css', 'js');   // Builds both the CSS and the JS.
```

run it with ` docker-compose run --rm --user 1000:1000 node ./materialBuild.js`

But unfortunately I've got `standard_init_linux.go:190: exec user process caused "exec format error"`.

Any idea what might be a problem?

**Comment by Splaktar** [comment]
What version of NodeJS is being used in your container?

**Comment by Szymon-dziewonski** [comment]
Hey @Splaktar thanks for reply, my node version is v8.9.4

**Comment by Splaktar** [comment]
No ideas based on this limited information, sorry. Can you run it locally outside of the container or when ssh'd into the container? Have you been able to debug it at all?

**Comment by Splaktar** [comment]
@KEINOS thank you for looking into this some. I'm going to close this as it appears to be related to the container configuration rather than AngularJS Material or these tools.
