### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: no mixin named checkbox-primary

### ISSUE THREAD

**Issue by norkunas** [angular/material-tools#44]
After updating material to 1.1.23, I'm getting this error when building.

```
(node:23488) UnhandledPromiseRejectionWarning: Error: no mixin named checkbox-primary
    at Object.module.exports.renderSync (/home/norkunas/www/node_modules/node-sass/lib/index.js:441:16)
    at Function.CSSBuilder._compileSCSS (/home/norkunas/www/node_modules/angular-material-tools/lib/builders/CSSBuilder.js:49:29)
    at MaterialTools.MaterialBuilder._buildTheme (/home/norkunas/www/node_modules/angular-material-tools/lib/builders/MaterialBuilder.js:71:48)
    at /home/norkunas/www/gulp/styles.js:39:28
```

**Comment by Splaktar** [comment]
Can you provide any reproduction steps? I'm seeing `npm run test:versions` pass in current master and with PR https://github.com/angular/material-tools/pull/45.

**Comment by norkunas** [comment]
package.json:
```
{
  "dependencies": {
    "angular": "^1.8.0",
    "angular-material": "^1.1.23",
    "angular-material-tools": "^1.0.0-beta.9",
    "gulp": "^3.9.1"
  }
}
```

gulpfile.js:
```
const gulp = require('gulp');
const MaterialTools = require('angular-material-tools');
const builder = new MaterialTools({
  destination: 'build',
  version: 'local',
  themes: []
});

gulp.task('styles', [], function (done) {
  builder._getData().then(function (buildData) {
    builder._buildTheme(buildData);
    done();
  });
});
```

For some reason it's enough to pass the empty `themes` key to the builder and then it fails/without it succeeds..

**Comment by norkunas** [comment]
Will this be fixed? :)

**Comment by Splaktar** [comment]
Yes, we plan to fix this, but we've been heads down on getting the `1.2.0` release out. Now that that is done, this issue can get some attention.

**Comment by Splaktar** [comment]
OK, it looks like the 1.0.0-beta.9 release was bad. It included the whole repo w/o the `dist/` folder and didn't publish the built files in `dist/` as it should have. 

The workaround for now is to use `"angular-material-tools": "1.0.0-beta.8",`

I'll try to get this resolved and put out another release soon.

**Comment by Splaktar** [comment]
It looks like the change of `mixins.scss` to `_mixins.scss` in `1.1.23` caused this exception.

I made [this repo](https://github.com/DevIntent/material-tools-test/tree/0.0.1) to help debug this.

I fixed this exception in https://github.com/angular/material-tools/commit/dc8e6be2b985548f0ffecc48e978df7101184e4c, but that just led to another exception:
```
(node:10260) UnhandledPromiseRejectionWarning: TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at ThemeBuilder.build (/Users/splaktar/Git/devintent/material-tools-test/node_modules/angular-material-tools/lib/builders/ThemeBuilder.js:40:14)
    at MaterialTools.MaterialBuilder._buildTheme (/Users/splaktar/Git/devintent/material-tools-test/node_modules/angular-material-tools/lib/builders/MaterialBuilder.js:73:50)
    at /Users/splaktar/Git/devintent/material-tools-test/gulpfile.js:11:13
(node:10260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'll investigate this next.

**Comment by Splaktar** [comment]
@norkunas thank you very much for this report and the reminders to follow up on it!

I believe that these issues are all addressed. Can you please give `1.0.0-rc.3` a try and let us know how it works for you?

If it looks good for you, we will release an official `1.0.0`.

**Comment by norkunas** [comment]
Thank you for fixing it :) I'll check it on tuesday.

**Comment by norkunas** [comment]
I confirm it works for us upgradint to material v1.2 :) thank you once more.

**Comment by Splaktar** [comment]
@norkunas great! Thank you very much for taking the time to try it out and report back here. Much appreciated ⭐
